apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuber-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /health/
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/(.+)/health/
            pathType: ImplementationSpecific
            backend:
              service:
                name: myapp1-svc
                port:
                  number: 8000